export const elementById = {
    convertTrashToMetal: document.getElementById("trash_to_metal_btn"),
    convertMetalToBronze: document.getElementById("metal_to_bronze_btn"),
    convertBronzeToSilver: document.getElementById("bronze_to_silver_btn"),
    convertSilverToGold: document.getElementById("silver_to_golden_btn"),
    convertGoldToPlatinum: document.getElementById("golden_to_platinum_btn"),

    createMetalTower: document.getElementById("create_metal_tower_btn"),
    createBronzeTower: document.getElementById("create_bronze_tower_btn"),
    createSilverTower: document.getElementById("create_silver_tower_btn"),
    createGoldenTower: document.getElementById("create_golden_tower_btn"),
    createPlatinumTower: document.getElementById("create_platinum_tower_btn"),

    upgradeMetalTower: document.getElementById("upgrade_metal_towers_btn"),
    upgradeBronzeTower: document.getElementById("upgrade_bronze_towers_btn"),
    upgradeSilverTower: document.getElementById("upgrade_silver_towers_btn"),
    upgradeGoldTower: document.getElementById("upgrade_golden_towers_btn"),
    upgradePlatinumTower: document.getElementById("upgrade_platinum_towers_btn"),

    trashMoneyCount: document.getElementById("trash_money_count"),
    metalMoneyCount: document.getElementById("metal_money_count"),
    bronzeMoneyCount: document.getElementById("bronze_money_count"),
    silverMoneyCount: document.getElementById("silver_money_count"),
    goldenMoneyCount: document.getElementById("golden_money_count"),
    platinumMoneyCount: document.getElementById("platinum_money_count"),

    trashMoneyRate: document.getElementById("trash_money_rate"),
    metalMoneyRate: document.getElementById("metal_money_rate"),
    bronzeMoneyRate: document.getElementById("bronze_money_rate"),
    silverMoneyRate: document.getElementById("silver_money_rate"),
    goldenMoneyRate: document.getElementById("golden_money_rate"),
    platinumMoneyRate: document.getElementById("platinum_money_rate"),

    metalTowerCount: document.getElementById("metal_tower_count"),
    bronzeTowerCount: document.getElementById("bronze_tower_count"),
    silverTowerCount: document.getElementById("silver_tower_count"),
    goldenTowerCount: document.getElementById("golden_tower_count"),
    platinumTowerCount: document.getElementById("platinum_tower_count"),

    createMetalTowerCost: document.getElementById("get_create_metal_tower_cost"),
    createBronzeTowerCost: document.getElementById("get_create_bronze_tower_cost"),
    createSilverTowerCost: document.getElementById("get_create_silver_tower_cost"),
    createGoldenTowerCost: document.getElementById("get_create_gold_tower_cost"),
    createPlatinumTowerCost: document.getElementById("get_create_platinum_tower_cost"),

    metalTowerLevel: document.getElementById("get_metal_tower_level"),
    bronzeTowerLevel: document.getElementById("get_bronze_tower_level"),
    silverTowerLevel: document.getElementById("get_silver_tower_level"),
    goldenTowerLevel: document.getElementById("get_golden_tower_level"),
    platinumTowerLevel: document.getElementById("get_platinum_tower_level"),

    upgradeMetalTowerCost: document.getElementById("get_upgrade_metal_tower_cost"),
    upgradeBronzeTowerCost: document.getElementById("get_upgrade_bronze_tower_cost"),
    upgradeSilverTowerCost: document.getElementById("get_upgrade_silver_tower_cost"),
    upgradeGoldenTowerCost: document.getElementById("get_upgrade_golden_tower_cost"),
    upgradePlatinumTowerCost: document.getElementById("get_upgrade_platinum_tower_cost"),
};